-- Migration: Add missing foreign key indexes

-- CREATE INDEX IF NOT EXISTS idx_auth_mfa_challenges_factor_id ON auth.mfa_challenges (factor_id);
CREATE INDEX IF NOT EXISTS idx_specialty_region ON specialty (region);
-- CREATE INDEX IF NOT EXISTS idx_auth_saml_relay_states_flow_state_id ON auth.saml_relay_states (flow_state_id);
-- CREATE INDEX IF NOT EXISTS idx_auth_oauth_authorizations_client_id ON auth.oauth_authorizations (client_id);
-- CREATE INDEX IF NOT EXISTS idx_auth_oauth_authorizations_user_id ON auth.oauth_authorizations (user_id);
-- CREATE INDEX IF NOT EXISTS idx_storage_s3_multipart_uploads_parts_upload_id ON storage.s3_multipart_uploads_parts (upload_id);
-- CREATE INDEX IF NOT EXISTS idx_storage_s3_multipart_uploads_parts_bucket_id ON storage.s3_multipart_uploads_parts (bucket_id);
CREATE INDEX IF NOT EXISTS idx_ingredient_submission_ingredient_id ON ingredient_submission (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_conversation_community_group_id ON conversation (community_group_id);
CREATE INDEX IF NOT EXISTS idx_recipe_parent_recipe_id ON recipe (parent_recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredient_translation_unit ON recipe_ingredient_translation (unit);
CREATE INDEX IF NOT EXISTS idx_conversation_created_by ON conversation (created_by);
CREATE INDEX IF NOT EXISTS idx_ingredient_category ON ingredient (category);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredient_ingredient_id ON recipe_ingredient (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredient_unit ON recipe_ingredient (unit);
CREATE INDEX IF NOT EXISTS idx_recipe_image_recipe_id ON recipe_image (recipe_id);
CREATE INDEX IF NOT EXISTS idx_meal_consumption_meal_plan_entry_id ON meal_consumption (meal_plan_entry_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_user_id ON shopping_list (user_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_item_shopping_list_id ON shopping_list_item (shopping_list_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_item_ingredient_id ON shopping_list_item (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_shopping_list_item_unit ON shopping_list_item (unit);
CREATE INDEX IF NOT EXISTS idx_fan_subscription_history_subscription_id ON fan_subscription_history (subscription_id);
CREATE INDEX IF NOT EXISTS idx_creator_revenue_log_recipe_id ON creator_revenue_log (recipe_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_sender_id ON chat_message (sender_id);
CREATE INDEX IF NOT EXISTS idx_chat_message_recipe_id ON chat_message (recipe_id);
CREATE INDEX IF NOT EXISTS idx_community_group_creator_id ON community_group (creator_id);
CREATE INDEX IF NOT EXISTS idx_conversation_request_requester_id ON conversation_request (requester_id);
CREATE INDEX IF NOT EXISTS idx_conversation_request_recipient_id ON conversation_request (recipient_id);
CREATE INDEX IF NOT EXISTS idx_push_token_user_id ON push_token (user_id);
CREATE INDEX IF NOT EXISTS idx_support_message_user_id ON support_message (user_id);
CREATE INDEX IF NOT EXISTS idx_ai_conversation_user_id ON ai_conversation (user_id);
CREATE INDEX IF NOT EXISTS idx_cooking_session_ingredient_ingredient_id ON cooking_session_ingredient (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_meal_ingredient_ingredient_id ON meal_ingredient (ingredient_id);
CREATE INDEX IF NOT EXISTS idx_group_invite_inviter_id ON group_invite (inviter_id);
CREATE INDEX IF NOT EXISTS idx_community_group_region_code ON community_group (region_code);
CREATE INDEX IF NOT EXISTS idx_allergen_suggestion_user_id ON allergen_suggestion (user_id);
CREATE INDEX IF NOT EXISTS idx_meal_consumption_creator_id ON meal_consumption (creator_id);

